### ISSUE TITLE
Improvement: group access under the specified paths

### ISSUE THREAD

**Issue by cgwr** [weseek/growi#423]
I have been waiting for "group access" feature. Excellent!
But, I hope  a little more improvement to restrict not only the page but also all pages under the path.  
It seems I must restrict each page one by one in the latest growi (3.0.13)

**Comment by yuki-takei** [comment]
@cgwr Thank you for your comment.
That might be useful, but there are several way to implement, so I think it's difficult to determine what is the best.

For instance, what do you think about the below functions?

- You can select default grant option from [Public/Just me/...] when creating new page in `/admin/app` settings
- You can also select the default grant option 'Inherit one of parent page'
  - The parent grant value will be set when creating new page in default

This is the simplest way, but we might not satisfy because these functions doesn't affect when moving pages.

**Comment by cgwr** [comment]
@yuki-takei 
Thanks for your reply. Sounds great!

>  'Inherit one of parent page'

This might be my true requirement.
I think some users want to create “Just me” area, too.
```
/user/{username}/private/
/user/{username}/private/tasks
/user/{username}/private/tasks/awesome-plan
 ```
Your suggestion will also help this.

==========

Sorry I have random comments.
Just a thought, “Just me” could be a kind of group. “Public”, too.
So, there might be another way . 

The current editor’s footer is as such :

Left dropdown (options)
* Public
* Anyone with the link
* Just me
* Only inside the group

Right dropdown (scope)
* group1
* group2
* …

My idea is as such :

Left checkboxes (options)

- [x] Create share link
- [x] Children inherit scope

Right dropdown (scope)

* Public
* Just me
* group1
* group2
* …

This enable below configurations:
```
/group1-pages/                     (group1 scope)
/group1-pages/page1                (inherited group1 scope)
/group1-pages/page1/want-to-share  (inherited group1 scope + share link)
```
===========

By the way,  your suggestion is surely useful.
That's enough for my team.

**Comment by yuki-takei** [comment]
Relate to #741

**Comment by yuki-takei** [comment]
You can now set the scope more convenient!

Behavior at the moment
---------------------------

* When creating a new page, the scope of ascendant page will be retrieved
* Users can overwrite scopes of descendants from extended create/update button
    * ![image](https://user-images.githubusercontent.com/1638767/50338847-0247d100-0559-11e9-87f9-adaee0c00d50.png)

**Comment by cgwr** [comment]
@yuki-takei Thank you so much!

Our team has upgraded growi to v3.3.3 .
I think new feature will reduce our routines and mistakes.
